// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akuqvqbggqbnowapcbhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrdXF2cWJnZ3Fibm93YXBjYmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjAwMDEsImV4cCI6MjA1OTA5NjAwMX0.epHR49ygfIUH6KRW03VBMdxrNFZO-AmDd6qm-yoYUAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);